name: CI

on:
  push:
  pull_request:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Build Toolchain
      run: docker-compose build debian-lazbuild

    - name: Build vCardStudio
      run: docker-compose run debian-lazbuild
    
    - name: Upload deb
      with:
        path: dist/*
